name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
    
jobs:
  backup:
    name: Backup production Organization
    runs-on: ubuntu-latest
    environment: 'My Environment Name'
    steps:
      - name: Authenticate to Git & checkout the repo
        uses: actions/checkout@v3
      - name: Authenticate to Coveo
        run: npx @coveo/cli auth:token -t ${{secrets.MY_API_KEY}}
      - name: Backup organization
        run: |
          npx @coveo/cli org:resources:pull -f
          git add .
          git commit -m "backup my coveo organization"
          git push
